### ISSUE TITLE
Intellisene documentation does not show up

### ISSUE THREAD

**Issue by nightowl286** [naudio/NAudio#1047]
It seems that after getting the nuget package, the documentation is not included with it. It is not visible through intellisense nor when viewed with the ILSpy decompiler (usually documentation is visible there). I found the issue #917 which seems to be relevant, and has been marked as closed, but it doesn't seem to solve the issue.

I am not sure why it is still a problem, but I would assume it is to do with the conditional flag on the `GenerateDocumentationFile` property.

**Comment by markheath** [comment]
OK, have tried making the change for the next version

**Comment by KPHIBYE** [comment]
I found the cause of the missing documentation. The commit that is tagged `v2.1.0` is e5e4fd6980d5c370800dfb8e9d81cb1d1ca796ee which is three commits behind 0cd2aba4dc69353cb25e5cf09d3c9d63f19daf9a which was created because of my issue. So the reason was that the old fix was just too late for the 2.1.0 release.

The new fix in 5d102d39b4e790ab96d2eeb4e66047773e0cd10d just changed that the documentation is now created each time the code is compiled compared to previously when it would just be created for release builds.
