### ISSUE TITLE
Problem with JointStereo in mp3

### ISSUE THREAD

**Issue by Nekromancer** [naudio/NAudio#116]
I got an exception with message 

`Got a frame with channel mode JointStereo, in an MP3 with 1 channels. Mp3FileReader does not support changes to channel count.`

on line:

`using (var reader = new Mp3FileReader(path))`

This mp3 file is created by writing bytes from stream directly to file. Can i force NAudio to open such file?

**Comment by markheath** [comment]
This is a known issue with NAudio, usually caused by album art at the start of the file being misinterpreted as valid MP3 frames. Really the correct fix is for NAudio to only decide it has the correct WaveFormat for the MP3 file if it gets many (e.g. 10 or more) MP3 frames in the same format. You can however use the ReadNextFrame method on the MP3 file to access the raw frames directly, and you could even pass them through a decoder yourself.

**Comment by Nekromancer** [comment]
Can you point me in the right direction here?

My goal is to produce as small mp3 file as possible. I'm using NAudio.Lame to convert mp3 to 16 kbits (since MediaFoundation has it's limits) like this:

```
        public static void DownsampleFileNAudio(string path, string targetPath)
        {
            using (var reader = new Mp3FileReader(path))
            using (var writer = new LameMP3FileWriter(targetPath, reader.WaveFormat, 16))
                reader.CopyTo(writer);
        }
```

**Comment by markheath** [comment]
`NAudio.Lame` is not maintained by me so I don't know how to set the bitrate, but what you've written looks like it should work (although I tend to avoid CopyTo since I don't know what block sizes it will read in). When I create MP3s myself, I tend to call LAME.exe directly using the technique I describe [here](http://www.codeproject.com/Articles/501521/How-to-convert-between-most-audio-formats-in-NET)

**Comment by Nekromancer** [comment]
We are doing a lot of conversions at one. Unfortunetely calling lame.exe is flawed in this way and tends to crash.
