### ISSUE TITLE
Panning property of WaveChannel32 not working as expected

### ISSUE THREAD

**Issue by aaronallen8455** [naudio/NAudio#168]
I'm building an application where the Pan property of a WaveChannel32 is controlled by a WPF slider control.
The WaveStream that feeds the WaveChannel32 reads from a stereo 512kbps .wav file and the WaveChannel32 is added to a MixingSampleProvider (there are multiple tracks that have independent panning controls).
The slider has range -1 to 1. When the slider is centered (pan=0), the result is as expected. However, if the slider is moved slightly in either direction, the sound is panned almost completely in that direction. The desired effect is smooth panning from left to right.
I've thought about having two mono audio sources for each audio source where one is panned all the way left and the other to the right and then having the pan slider simply control the volume between the two. I hope there's a better solution than that.

**Comment by markheath** [comment]
`WaveChannel32` is a very old class that I only leave in NAudio because so many old tutorials suggest using it. But the preferred way is to use `PanningSampleProvider` which has a configurable panning strategy so you can get the exact behaviour you want. There are four strategies in the box plus the ability to create your own.

**Comment by aaronallen8455** [comment]
That works, Thanks!
