### ISSUE TITLE
Add support .NET Portable or .NET Standard.

### ISSUE THREAD

**Issue by JunielKatarn** [naudio/NAudio#173]
Can't add NAudio as a NuGet dependency for the following cases:

1. .NET Portable (Xamarin.Forms) project:
```
Could not install package 'NAudio 1.8.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.0,Profile=Profile24', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```
2. .NET Standard
```
Package NAudio 1.8.0 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package NAudio 1.8.0 supports:
  - net35 (.NETFramework,Version=v3.5)
  - win8 (Windows,Version=v8.0)
One or more packages are incompatible with .NETStandard,Version=v1.4.
Package restore failed.
```

**Comment by markheath** [comment]
NAudio is not cross-platform capable as it relies very heavily on Windows audio and codec APIs. It might be possible in the future to create a cut-down version of NAudio containing only bits that would work cross-platform. But as things stand, it only really makes sense to use NAudio on Windows and so I'm not clear what benefit targeting netstandard would give.

**Comment by residuum** [comment]
IMHO a version of NAudio compatible with .NET Standard would make sense, if you are willing to split the NAudio API and binding to Windows API.

That would be two packages, `NAudio.Core` and `NAudio.Windows`, while others could write different API bindings for different platforms.

I did this with `NAudio.Jack`, although it only implements `IWaveIn` and `IWaveOut`:

https://github.com/residuum/JackSharp/tree/master/NAudio.Jack

**Comment by markheath** [comment]
sure, that would be the right way to do it. I haven't got any active plans to work on this at the moment though

**Comment by JunielKatarn** [comment]
Hi.
The issue is not only about multiple operating systems.

After playing around with different versions, I found my .NET Portable (still Windows only) app can import NAudio 1.5 fine, but not 1.8.0, because the latter doen't include the .NET Portable version as one of its targets.

I'll try to take a look, but this issue may be resolved by just adding another target framework in the build files.

**Comment by markheath** [comment]
there's a .NET Standard build in the works (look at the netstandard branch) which I'm hoping will be used for NAudio 1.9. It doesn't support all the classes in the regular .NET framework version of NAudio, but it does allow a lot of the library to be used from .NET core or other .NET Standard 2.0 platforms

**Comment by GuardianArchangelJohn** [comment]
I wanted to ask about this as well, and here's why. I'm on the MacBook, building a managed database platform and web ASP.NET Core API backend platform that works across Xamarin, Unity3D, and ASP.NET Core, because I want to go across web, desktop, mobile, and Unity3D with C#. 

End goal? So my database platform lets you tell it which fields you want over the web it creates a JSON configuration using a data-first sort of approach since I cut the ORM out completely, it generates your data tables, runtime objects, as well as self-reverse engineers the source code so that you can extend it with code in your own project, or you could also build from code-first and go the other way, which is quite nice. Think of it sort of like Django in Python but for .NET Core, since Django lets you use command-line tools to create the code from your database, well mine does a similar function without the need for command-line tools you can build the database and the api as a user over the web all in one go with administrative tools behind it so that you can create some interesting things with it like say a social media website or home automation or websites dealing with robotics communication.

So I want to store the music in a table, it creates the .NET Core infrastructure necessary to make it a backend web API, stream it into Unity3D, with also supplemental related tables that define colors for my LIFX lightbulbs that control the lighting for certain lights at specific time intervals in a song, giving you a sort of automated light show with also 3D graphics going on in Unity, which could be quite rad as I'm itching to experiment on. So my thanks to you markheath for at least helping get me this far, because I've been fumbling a bit trying to learn modified discrete cosine transforms and the like to decompress mp3 frames on my own since my math skills aren't quite up to par when I want them to be. 

Given that Unity3D still doesn't allow native mp3 streaming even on OSX despite that the mp3 format patent has expired, when using their WWW class in Unity to load an AudioClip into an AudioSource you can't load an mp3 or you get the "unsupported on this platform" error, the bottleneck is basically Unity on a lot of fronts, so you have to load ogg or some other format typically speaking. 

My web server on the other hand supports loading in mp3s, because only in rare instances might my originating song be in ogg. So what I wanted to do, is store the data as mp3 server-side, and allow for conversion into ogg either on a database insert event or on the fly when getting it from the api. Now Naudio/Vorbis only supports decoding vorbis, but .NET-Ogg-Vorbis-Encoder by Steve Lillis might be able to help.

Here's the problem though, NAudio fails on Visual Studio for Mac on creating a new AcmMp3FrameDecompressor because AcmInterop needs msacm32.dll, which doesn't exist of course being a Windows dll. Is there perhaps an alternate that I can use? There's a lot in NAudio that's tied to Windows and Winforms bindings, looks like you got some of the Winforms out of there, which is greatly appreciated as it will help NAudio be more cross-platform accessible. I'm wondering what kind of effort is needed in an Mp3FrameDecompressor that will support OSX and how much complexity is in msacm32.dll?

**Comment by feliwir** [comment]
Any updates on this?

**Comment by markheath** [comment]
Slow progress at the moment I'm afraid, as I'm working on other projects at the moment. I'm hoping there might be some time to look at this later this year.
My thoughts are that it's probably time to do an NAudio 2.0 which makes multiple improvements and breaks different APIs out into separate assemblies so there can be a cross-platform core, with additional libraries for wrapeprs for specific Windows APIs.

**Comment by markheath** [comment]
Please try out the 1.9.0-preview2 package now on NuGet that targets netstandard (obviously not all features in the full net framework version of Windows are supported)

**Comment by sanekpr** [comment]
@markheath Is it possible to release the stable version 1.9.0 ? Or any planned date of release?

**Comment by markheath** [comment]
I've just published it! Let me know if there are any issues
