### ISSUE TITLE
Support for Streaming Additional Codecs

### ISSUE THREAD

**Issue by max-erler** [naudio/NAudio#211]
Hello,

Unless I am mistaken, I believe NAudio only supports streaming Mp3 from a Uri using the BufferedWaveProvider. Is there support for other codecs, and if not, can it be added? Specifically, I am interested in the following formats: AAC/MP4, MP3, HLS, PLS and M3U. 

This is a nice to have, and probably a pipe dream, but it would be great if there was an IWaveProvider implementation that could take a Uri and handle everything from there.

**Comment by markheath** [comment]
If you use `MediaFoundationReader` you can usually play AAC and various other formats from a Uri directly. Otherwise, its a lot more work as you'll need to manage downloading the audio from the network yourself, passing it to an appropriate codec and then buffering the decoded audio. So sadly, its not straightforward to implement.
