### ISSUE TITLE
NoDriver calling acmFormatSuggest - AZURE

### ISSUE THREAD

**Issue by mkariti** [naudio/NAudio#239]
Hi there,
Im moving my application from VM to webapp in Azure and Im getting the following error:
`  NAudio.Wave.Compression.AcmStream.SuggestPcmFormat(WaveFormat compressedFormat) +119
   NAudio.Wave.AcmMp3FrameDecompressor..ctor(WaveFormat sourceFormat) +29
   NAudio.Wave.Mp3FileReader.CreateAcmFrameDecompressor(WaveFormat mp3Format) +25
   NAudio.Wave.Mp3FileReader..ctor(Stream inputStream, FrameDecompressorBuilder frameDecompressorBuilder) +829
   NAudio.Wave.Mp3FileReader..ctor(Stream inputStream) +50`
Any input will be appreciated.
Regards,
mkariti

**Comment by mkariti** [comment]
Update: 
Moved my manipulation to wav rather than mp3 so no pcm is needed. all seems fine now.

**Comment by markheath** [comment]
ok glad you found a solution. for future reference, the issue is that in Azure you're likely running on a Windows Server VM that doesn't have the standard pack of ACM codecs that a regular desktop edition of Windows has. And if its a web-app you have no low-level access to the underlying server to install them
