### ISSUE TITLE
SimpleCompressorStream

### ISSUE THREAD

**Issue by gharig** [naudio/NAudio#249]
Hi,

I'm trying to use the SimpleCompressorStream in nAudio,  I see thaat I can set values for Attack, Release, Ratio, Threshold and Enabled.  When enabled is set to false nothing seem to happen it looks like it returns the sourceStream.  And I receive an error Wave File to long when I set Enable to true. CreateWaveFile("c:\tmp\wavOutputCompressor.wav", compressorStream) throws an error.

Maybe the problem is that I'm not using it correctly.  Is there a document or tutorial on using the SimpleCompressorStream?

Thanks
George

**Comment by markheath** [comment]
the wave file too long is because `CreateWaveFile` will keep going until it reaches the end of the source audio. But `SimpleCompressorStream` is a never-ending stream. So it is better to write your own loop pulling audio through until you've reached the end of the source audio file. `SimpleCompressorStream` was a very early experiment with effects in NAudio, and probably will be removed in future.
