### ISSUE TITLE
Application freezes when the  Stop /Pause method of AsioOut class are invoked at the end of the audio file

### ISSUE THREAD

**Issue by SR-TheCodingGenius** [naudio/NAudio#259]
I'm using NAudio library for my application, this library works really great, thanks to Mark Heath,
for providing such a opensource library .
But I came across a scenario where I was using AsioOut class  for play, pause and stop of Audio files against ASIO drivers (eg -ASIO4ALL), I noticed that my application hangs (UI thread) on the call of Stop method when the end of the audio file is reached, and I have to force fully close the application using task manager.

Is there any possible workarounds for it, for time being I'm forcing to stop the audio file 10 or 20 msec before it ends , where it works well, let me know if there is any better way as a workaround.

**Comment by markheath** [comment]
Yes, I think certain ASIO drivers can have an issue with Stop being called from within their callback method. I have contemplated taking it out. One way to fix the issue is to provide a never-ending stream to input (you can easily write your own, or repurpose something like one of the mixer classes). Then detect that playback has gone beyond the end of the source audio, and call Stop from outside.

**Comment by donperry** [comment]
Having this problem myself. How does one go about making a never ending stream to feed into my  _provider.AddSamples(x,x,x) function?

**Comment by markheath** [comment]
A never ending stream is an `ISampleProvider` or `IWaveProvider` whose `Read` method never returns 0 - it always returns the number of bytes asked for. Of course, it should zero out the buffer as well if it doesn't have any actual audio to provide.

I think it would also be a good idea for `AsioOut` to support optionally turning off auto-stop on reaching the end of the input audio stream

**Comment by markheath** [comment]
It seems that this issue is cropping up a lot more frequently. I've made an update to `AsioOut` so that it has an `AutoStop` property, which now defaults to false. This means that when the end of the input `IWaveProvider` is reached, the `AsioOut` device will just carry on playing silence indefinitely. You can detect this by using the new `HasReachedEnd` end property which will be set to true if all the audio from the input `IWaveProvider` has been consumed. This allows you to call `AsioOut.Stop` from your application when its done.
