### ISSUE TITLE
COM Issue

### ISSUE THREAD

**Issue by ArizonaInkStudios** [naudio/NAudio#425]
I have a class that holds the MMDevice. If that class is called from an event being raised, the device (which is a private member of the class) is no longer valid. I get a FriendlyName and DeviceFriendlyName but the ID is invalid and throws:
`Exception thrown: 'System.InvalidCastException' in NAudio.dll`

`21940 [19] ERROR Karaoke.App (null) - Unable to cast COM object of type 'System.__ComObject' to interface type 'NAudio.CoreAudioApi.Interfaces.IMMDevice'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{D666063F-1587-4E43-81F1-B948E807363F}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).`

`System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'NAudio.CoreAudioApi.Interfaces.IMMDevice'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{D666063F-1587-4E43-81F1-B948E807363F}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).`

`at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)`

`at NAudio.CoreAudioApi.Interfaces.IMMDevice.Activate(Guid& id, ClsCtx clsCtx, IntPtr activationParams, Object& interfacePointer)`

`at NAudio.CoreAudioApi.MMDevice.GetAudioClient()`

`at NAudio.Wave.WasapiOut..ctor(MMDevice device, AudioClientShareMode shareMode, Boolean useEventSync, Int32 latency)`

`...`

`at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)`

`at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)`

`at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)`

`at System.Threading.ThreadHelper.ThreadStart()`

`An unhandled exception of type 'System.InvalidCastException' occurred in NAudio.dll`

`Unable to cast COM object of type 'System.__ComObject' to interface type 'NAudio.CoreAudioApi.Interfaces.IMMDevice'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{D666063F-1587-4E43-81F1-B948E807363F}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).`

Any suggestions or ideas as to why this is happening?

**Comment by markheath** [comment]
hmm, not sure. what operating system are you on?

**Comment by ArizonaInkStudios** [comment]
Windows 10 Professional

**Comment by LenneRoijmans** [comment]
I'm having the same issue. Also Win 10 Pro.

**Comment by STL1811** [comment]
So have I

**Comment by markheath** [comment]
This could be a threading issue - are you calling the property from the same thread it was created on?

**Comment by STL1811** [comment]
Yes, it was. I changed the way I use it.
Thanks

**Comment by ArizonaInkStudios** [comment]
I am reviewing how I am calling this to ensure the same thread is being used. I believe I am, but I want to confirm that assumption.

**Comment by ArizonaInkStudios** [comment]
Apparently I changed something that caused this to not be an issue anymore. I have tried to duplicate it and (of course) it does not fail anymore. Thank you for your help and I appreciate the feedback and the collaboration! Unless anyone else needs assistance on this issue, I would think we could close it.

**Comment by markheath** [comment]
great, glad to hear it's working again for you

**Comment by sajeebchandan** [comment]
My app was throwing this exception. I've gathered some insight about this.

- The COM object requires all thread to run

- If you're trying to run this object from another thread be sure that thread is running

- If you program is running on `STAThread` and you are using this COM Object into a `Task` or another `Thread` then it will throw an exception like this.

So Please be sure that your program is running under `MTAThread` while using the COM object into a `Task` or `Thread`.

Thank you.
Special thanks to @markheath for creating such an awesome audio library.

**Comment by Nicks182** [comment]
Sorry to resurrect this, but I just ran into the same issue and found a way, _by accident_, to make it work without making huge changes to what I'm doing. As a bit of a noob I don't fully understand things and I'm unsure what to research here.

Anyway, I have a web front end that talks to a C# back end using SignalR. I'm new to SignalR as well, but my very much a **prototype/experiment** was going well until I tried to get 'MMDevice.AudioMeterInformation.MasterPeakValue'. This was quite confusing as I could get the value for a 'AudioSessionControl' just fine in the same call. 

After some googling and finding this thread, I tried to pull the value at the same time I load and setup everything and I could get the value just fine checking it with a break point. However, I then let it run I didn't get the error I got before and my visuals were updating perfectly fine. More confused I removed the code during setup and the error came back. 

For now, as part of my experiment, I'm getting the value once during setup and then after that I can pull the value whenever I want using SignalR with no errors. This at least allows me to continue figuring out the rest of what I want to try and build.

The plan was to build a hacky mess to learn and then rebuild from scratch and hopefully then do things more proper-ish.

So I have 2 questions:
Is this expected behavior?
My "solution" seems very much like a workaround... what should I be researching to learn how to handle this properly?

Again, sorry for resurrecting this.
