### ISSUE TITLE
"Expecting PCM input" exception appeared when using VolumeWaveProvider

### ISSUE THREAD

**Issue by huming2207** [naudio/NAudio#46]
Hi,

After asking the last issue thread, I've tried using the solution you've mentioned before (http://markheath.net/post/fire-and-forget-audio-playback-with) for mixing several WAV wave files together to play. In order to set the volume seperately, I modified **AudioPlaybackEngine class** a bit for satisfy my demand. 

Here is my modified code below:
```C#
public void PlaySound(string fileName, float volume = 1.0f)
{
       var input = new AudioFileReader(fileName);
       volumeControl = new VolumeWaveProvider16(input);
       volumeControl.Volume = volume;
       AddMixerInput(new AutoDisposeFileReader(input));
}
```

After I add "**VolumeWaveProvider**" and re-run the code, it threw out a exception which said it needs PCM input. But I did use a WAV wave file correctly, why it showed me this error?

Thanks and regards,
Jackson Hu

**Comment by markheath** [comment]
`AudioFileReader` already has a `Volume` property, so no need for the `VolumeWaveProvider16`. The reason you are seeing the error is that `AudioFileReader` converts PCM integer samples to IEEE float so it can be an `ISampleProvider`.

**Comment by huhu2207** [comment]
Okay thanks, I will try it!

Regards,
Jackson

**Comment by huhu2207** [comment]
Hi Mark,

I have a two new question. The first one is about is there any better ways to adjust the volume for cached sound which mentioned in your blog article. I've added something to the **CachedSound** Class and it does work, but then I can only adjust the volume when I load the wave files into the cache. And that's not very perfect, I need to adjust the volume when I run ``AudioPlaybackEngine.Instance.PlaySound()``.  Do you have any better idea to do that?

Another question is that I need to load a huge amounts of wave files to the cache (more than 80). So is there any better ways to "batch load" those files to specific variable instead of load them like ``var xxx = CachedSound(xxx.wav)`` separately?

Regards,
Jackson
