### ISSUE TITLE
GetPositionTimeSpan() is reporting incorrect results (1.9.0)

### ISSUE THREAD

**Issue by jtorjo** [naudio/NAudio#536]
I'm trying to show the accurate position while playing a mp3 file.
Initially, I was using `reader_.CurrentTime.TotalMilliseconds;` but this is not very accurate (seems like it works on 100ms increments). 

Then I tried to use `wave_?.GetPositionTimeSpan().TotalMilliseconds` but this is not working correctly. It always starts from zero, and goes onwards, regardless of the position in the stream.

Am I doing something wrong?

**Comment by markheath** [comment]
The position on the reader simply says where the output device has read to, and will depend on the buffer size. It will be slightly ahead of playback since the sound device reads ahead. If you use smaller buffer sizes, that will help a bit.

The position on the output device is more accurate in terms of where playback is up to, but as you have noticed, doesn't know anything about where in the file it is. It's just reporting the number of bytes played since playback started.

So at the moment, for more accurate position reporting, you need to do your own tracking of how the wave output device position maps to file position, which is fairly complex I'm afraid.

**Comment by jtorjo** [comment]
Got it, thanks.
I have a workaround that may work - will test in a bit.
