### ISSUE TITLE
How to understand the DesiredLatency and NumberOfBuffers property of WaveOut class?

### ISSUE THREAD

**Issue by TonyDragonlake** [naudio/NAudio#687]
Hi,
First of all, thank you very much for the code you contributed.
I have learned your source code, but I am confused about the behavior of the `WaveOut `class when playing audio files.
Two properties of `WaveOut`, `DesiredLatency` and `NumberOfBuffers`, seem to limit the buffer size of the `Read` method in `WaveStream`.
In the WpfDemo,
`NumberOfBuffers = 2`.
When playing audio, in the `WaveOutBuffer.OnDone` method,
WaveOutBuffer.buffer.Length = 38400.
38400*2 is **much smaller than** the size of the data in the audio file.
But it **CAN** play the entire audio file.
I want to know why.

**Comment by neilbgr** [comment]
It's a very good question!
Has anyone got a response pls?

**Comment by mdcdi1315** [comment]
The answer is pretty much simple: everything in programming cannot be fetched on the entirety because we would require a lot of RAM to just load for example a 50 MB file.
Buffers are a convenient solution for fetching parts of the file without sacrificing loads of useful RAM.
The same happens here. 
In fact, the desired latency expresses the time in milliseconds before new I/O requests are done.
If you increase the latency, you increase the underlying buffer size, thus you need less I/O requests but you need more RAM to save the buffer data.
