### ISSUE TITLE
Disposable Wave- / SampleProviders

### ISSUE THREAD

**Issue by NeoLegends** [naudio/NAudio#80]
Hi,

I'd like to ask why the ISampleProviders are not disposable. If there is a specific reason for this, I'd like to know the best practice for dealing with sample sources that need to be disposed. It's a little cumbersome to store all sample sources that need to be disposed along the chain and dispose them manually.

**Comment by markheath** [comment]
the original `WaveStream` base class was disposable, but this turned out to be a huge pain when using a decorator pattern, as you have many audio pipeline components that simply pass on data from their source, and you end up needing to pass through calls to Dispose. Even then, there was confusion about whose responsibility it was to call Dispose (e.g. if I dispose a mixer, should its inputs be disposed?), and so that meant we needed the `IgnoreDisposeStream`. So I decided for `IWaveProvider` and `ISampleProvider` that they would not be disposable. So I recommend if you have disposable components, just have a class that implements both interfaces and manage it yourself.

**Comment by NeoLegends** [comment]
Alright. I was asking because I'm integrating libspotify into my application, and it needs to be cleanly disposed.
