### ISSUE TITLE
How do I get the precise position of playback?

### ISSUE THREAD

**Issue by notexplosive** [naudio/NAudio#812]
I'm building a tool that requires a very precise playback position of a sound. My preference is a floating point value (in seconds) that represents the current playback position. I say "very precise" but 4 or 5 decimal places will do.

My first attempt was `(float) this.audioReader.Position / this.audioReader.WaveFormat.AverageBytesPerSecond;` which gives me about 2 decimal places worth of precision.

Is there any way I can squeeze more precision out of playback position?

**Comment by markheath** [comment]
Take a look at the `IWavePosition` interface which tells you exactly how much audio the soundcard has played. Obviously you need to take care how you convert this into the position within the source audio, because just because you have been playing audio for 30 seconds doesn't mean that you are 30 seconds into a file - you might have repositioned during playback
