### ISSUE TITLE
Not working in .net Maui

### ISSUE THREAD

**Issue by jcmontoya** [naudio/NAudio#903]
I tried this code:

  ```
private void PlayBeep() {

        outputDevice = new WaveOutEvent();
        audioFile = new AudioFileReader(Path.Combine(AppContext.BaseDirectory, "beep.mp3"));
        outputDevice.Init(audioFile);
        outputDevice.Play();

        outputDevice.Dispose();
        outputDevice = null;
        audioFile.Dispose();
        audioFile = null;
    }
```

 No sound in windows, Crashes the app in Android.

**Comment by markheath** [comment]
NAudio has no way to play audio on Android since the audio playback wrappers it provides are for Windows APIs. I haven't used MAUI myself, but I guess there may be some kind of audio playback API as part of the platform, in which case you should use that if possible instead of NAudio.

For Windows, the issue with your code is that you dispose the output device immediately. `Play` just means start playing. It returns immediately, so you're closing the output device before it has a chance to play anything
