### ISSUE TITLE
Some questions: MP3 licensing and more

### ISSUE THREAD

**Issue by tzachshabtay** [naudio/NAudio#98]
Hi, I have a few questions about the library:

1. Licensing- I see that you're using Ms-PL for your license, which is a permissive license, but also support MP3, which has strict licensing rules. Isn't that a contradiction? I've seen other projects that separate MP3 into a separate project and give it a different license for that reason.
I'm very weak in understanding legalities so I may be way off. Can somebody shed some light on this?

2. I see a corefx compilation flag in the source, but to my understanding the project is currently windows only. Is dot net core supported, or an ongoing process, or some effort that was abandoned? Or in short, what's the status on dot net core development?

3. Is there a need to continue support for the Windows8 project? Doesn't the Windows Universal project cover it completely?

Thanks.

**Comment by markheath** [comment]
1. NAudio does not contain an MP3 codec. It simply allows you to use whatever codecs are already installed on your computer. In Windows, there is an MP3 codec that ships out of the box

2. There has been no work on a dot net core version of NAudio. I'm not sure how much sense it would make since a very large portion of NAudio is interop wrappers to Windows APIs.

3. Possibly not, although there were new things added in UWP that aren't present on Windows 8 (most notably the AudioGraph APIs)

**Comment by tzachshabtay** [comment]
Thanks for the quick reply.
Regarding dot net core, I actually wanted to reuse some code for wave manipulations, as a large part of it looks to be purely managed. I started working on extracting all possible code to a PCL library when I saw the corefx compilation flag and wondered if anybody was already working on something.

**Comment by jnm2** [comment]
.NET Core is not just about cross-plat either. I'm using it as much as possible for Windows projects because I like it better and I like the direction it's headed. I could easily see myself wanting to process audio in an ASP.NET Core website, for example, and NAudio is definitely the first place I'd look.

If NAudio did position itself as the de facto cross-platform library, I could see people getting good use out of it. Obviously that's a lot of work since you'd have to add Linux interop but ultimately that's not so different from selecting which driver you want to use anyway.

**Comment by residuum** [comment]
NAudio is cross-platform, as the Nuget packages can be used with Mono on Linux (and probably Mac OS X) as well.

The problem lies with using IO and audio codecs.

For IO I have created a NAudio.Jack, which binds to the low-latency, cross-platform Jack audio connection kit.
https://github.com/residuum/JackSharp
http://jackaudio.org/
